### ISSUE TITLE
Is this repo still supported?

### ISSUE THREAD

**Issue by bscott** [astaxie/beegae#23]
Hello,

I can get a simple app deployed using the example in the README, is this repo still maintained? @astaxie

**Comment by astaxie** [comment]
@someone1 maintain this repo

**Comment by someone1** [comment]
@bscott, you can or you can't?

I haven't updated the repo to 1.5 yet but you can still use beegae with beego 1.4.2.

Since Go on GAE is somewhat being pointed towards Managed VMs, I wanted to build in compatibility with the new libraries when they become more stable. In fact, I think this repo can go away if issue #1077 (https://github.com/astaxie/beego/issues/1077) is ever implemented in beego. Then adding GAE support should be trivial!
