### ISSUE TITLE
Build fail with goapp on window

### ISSUE THREAD

**Issue by thanyatad** [astaxie/beegae#26]
INFO     2016-02-24 16:41:18,815 devappserver2.py:769] Skipping SDK update check.
INFO     2016-02-24 16:41:18,874 api_server.py:205] Starting API server at: http://localhost:52480
INFO     2016-02-24 16:41:18,878 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-02-24 16:41:18,880 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2016-02-24 16:41:19,940 go_runtime.py:179] Failed to build Go application: (Executed command: D:\GoApp\g
oroot\bin\go-app-builder.exe -app_base D:\GoApp\gopath\src\demoapp\main -arch 6 -dynamic -goroot D:\GoApp\goroot
-nobuild_files ^^$ -unsafe -gopath D:\GoApp\gopath -print_extras_hash main.go)

2016/02/24 16:41:19 go-app-builder: Failed parsing input: parser: bad import "syscall" in conn.go from GOPATH

**Comment by jelmerdereus** [comment]
From the [KB](https://cloud.google.com/appengine/kb/)

The majority of pure Go packages work on Google App Engine. A package may not work because of one of these reasons:

The package imports **syscall **or unsafe.
The package uses cgo or assembly.
The package requires functions in packages that are locked down, such as writing to disk, or direct network access.

Does this answer your question @thanyatad ?

**Comment by jelmerdereus** [comment]
Can you please close it @astaxie ?
